# Generated by Django 3.2.6 on 2021-08-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(max_length=4, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('team1', models.CharField(blank=True, max_length=50, null=True)),
                ('team2', models.CharField(blank=True, max_length=50, null=True)),
                ('toss_winner', models.CharField(blank=True, max_length=50, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=5, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('dl_applied', models.BooleanField(default=0)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('win_by_runs', models.IntegerField(max_length=4, null=True)),
                ('win_by_wickets', models.IntegerField(max_length=2, null=True)),
                ('player_of_match', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire1', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(max_length=2, null=True)),
                ('batting_team', models.CharField(blank=True, max_length=50, null=True)),
                ('bowling_team', models.CharField(blank=True, max_length=50, null=True)),
                ('over', models.IntegerField(max_length=2, null=True)),
                ('ball', models.IntegerField(max_length=2, null=True)),
                ('batsman', models.CharField(blank=True, max_length=50, null=True)),
                ('non_striker', models.CharField(blank=True, max_length=50, null=True)),
                ('bowler', models.CharField(blank=True, max_length=5, null=True)),
                ('is_super_over', models.BooleanField(default=0)),
                ('wide_runs', models.IntegerField(max_length=2, null=True)),
                ('bye_runs', models.IntegerField(max_length=2, null=True)),
                ('legbye_runs', models.IntegerField(max_length=2, null=True)),
                ('noball_runs', models.IntegerField(max_length=2, null=True)),
                ('penalty_runs', models.IntegerField(max_length=2, null=True)),
                ('batsman_runs', models.IntegerField(max_length=3, null=True)),
                ('extra_runs', models.IntegerField(max_length=2, null=True)),
                ('total_runs', models.IntegerField(max_length=2, null=True)),
                ('player_dismissed', models.CharField(blank=True, max_length=50, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=10, null=True)),
                ('fielder', models.CharField(blank=True, max_length=50, null=True)),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats_report.matches')),
            ],
        ),
    ]
